<a href="https://colab.research.google.com/github/Aaditya117/SHALA-2020/blob/master/Assignment_1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [7]:
import numpy as np
a = np.random.rand(3,5)
b = np.random.rand(3,5)
print(a)
print(b)

[[0.60933382 0.83625059 0.84534561 0.48848499 0.82130636]
 [0.29999174 0.67449086 0.02458445 0.59715379 0.80057114]
 [0.98425108 0.97916133 0.60640817 0.94723585 0.21401224]]
[[0.39384836 0.02931087 0.42404017 0.45290561 0.57321032]
 [0.88417649 0.965292   0.95946323 0.2141937  0.05418753]
 [0.53055303 0.27350181 0.3306878  0.87722119 0.36589406]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all positive integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [23]:
c = np.arange(0,100,1,dtype= int).reshape(100,1)
d = np.zeros((3,3))
print(c)
print(d)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]
 [50]
 [51]
 [52]
 [53]
 [54]
 [55]
 [56]
 [57]
 [58]
 [59]
 [60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]
 [80]
 [81]
 [82]
 [83]
 [84]
 [85]
 [86]
 [87]
 [88]
 [89]
 [90]
 [91]
 [92]
 [93]
 [94]
 [95]
 [96]
 [97]
 [98]
 [99]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [16]:
e = [[1,2,3],[4,5,6],[7,8,9]]

e = np.asarray(e)
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [18]:
f = np.ones((5,5),dtype=int)
g = np.identity(5,dtype=int)
print(f)
print(g)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $d^\prime$ and print **YES** when the shapes of $d$ and $d^\prime$ are same. Otherwise print **NO**.

In [26]:
h = c.reshape((10,10))
d1 = h.flatten()
if (np.shape(d) == np.shape(d1)) :
   print("YES")
else:
   print("NO")   


NO


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [28]:
A = np.random.rand(2,10,5)
A1 = A.T
print(A1)


[[[0.71104685 0.6623061 ]
  [0.74093623 0.87524848]
  [0.71424123 0.4843228 ]
  [0.85793076 0.02614422]
  [0.50761846 0.38723363]
  [0.9056029  0.98340838]
  [0.11089677 0.67336378]
  [0.70887577 0.35038399]
  [0.8971782  0.49713544]
  [0.50038841 0.10966453]]

 [[0.76402948 0.41335631]
  [0.1914329  0.3398279 ]
  [0.56593499 0.22494482]
  [0.68092301 0.23644131]
  [0.04086589 0.21417074]
  [0.87534458 0.68845861]
  [0.51708686 0.17145617]
  [0.43718245 0.12660244]
  [0.71414039 0.15336922]
  [0.99142911 0.51436954]]

 [[0.13447926 0.11016308]
  [0.87536675 0.14706434]
  [0.67606394 0.5198422 ]
  [0.30100349 0.02038004]
  [0.23421196 0.78604489]
  [0.46862142 0.23308418]
  [0.43788618 0.37402613]
  [0.6472737  0.11420757]
  [0.3311725  0.05039316]
  [0.54714263 0.34888634]]

 [[0.54511137 0.23950655]
  [0.96115518 0.29292578]
  [0.12656018 0.31255678]
  [0.12526762 0.29069303]
  [0.04337903 0.92126425]
  [0.16745067 0.54258166]
  [0.21012455 0.30498353]
  [0.04887663 0.47201828]
  [0.9

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)



Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)




## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [0]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"



### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---





---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



###Normalization


---



1. Normalize the columns which have numerical data



---





---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.